# Generated by Django 4.2 on 2025-10-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LNapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField(max_length=300)),
                ('full_description', models.TextField()),
                ('image', models.ImageField(upload_to='case_studies/')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
