# Generated by Django 4.2 on 2025-10-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LNapp', '0002_casestudy'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='link',
            field=models.URLField(blank=True, help_text='Optional external link', null=True),
        ),
    ]
