# Generated by Django 4.2 on 2025-10-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LNapp', '0004_alter_casestudy_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='link',
            field=models.CharField(blank=True, help_text='Optional external link', max_length=500, null=True),
        ),
    ]
