# Generated by Django 4.2 on 2025-11-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LNapp', '0005_alter_casestudy_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
